# Generated by Django 3.2 on 2021-05-20 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordCommandStatus',
            fields=[
                ('command_id', models.UUIDField(default=uuid.UUID('0d11f80f-98a4-49ac-a18d-3df8f03d7d71'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Command ID')),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('SUCC', 'Succeeded'), ('FAIL', 'Failed')], max_length=4, verbose_name='Command Status')),
                ('timeout', models.DateTimeField(verbose_name='Command Callback Timeout')),
                ('error_message', models.CharField(blank=True, max_length=100, verbose_name='Error Message')),
            ],
        ),
    ]
