# Generated by Django 3.2.3 on 2021-06-01 02:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('discord_bot_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordcommandstatus',
            name='command_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Command ID'),
        ),
        migrations.CreateModel(
            name='ScavChannel',
            fields=[
                ('channel_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
