# Generated by Django 3.2.3 on 2021-06-02 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot_manager', '0003_alter_discordcommandstatus_command_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordcommandstatus',
            name='command_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Command Time'),
        ),
    ]
