# Generated by Django 3.2.3 on 2021-06-02 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot_manager', '0004_discordcommandstatus_command_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordcommandstatus',
            name='command_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Command Time'),
        ),
    ]
