# Generated by Django 3.2.5 on 2021-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot_manager', '0006_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Discord Role ID'),
        ),
    ]
