# Generated by Django 3.2.5 on 2021-08-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot_manager', '0007_alter_role_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Discord Role', 'verbose_name_plural': 'Discord Roles'},
        ),
    ]
