# Generated by Django 3.2.5 on 2021-08-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot_manager', '0009_channeltag_discordchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordOverwrite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Overwrite ID')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='User or Role ID')),
                ('type', models.IntegerField(choices=[(0, 'Role'), (1, 'Member')])),
                ('allow', models.PositiveBigIntegerField()),
                ('deny', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Discord Permission Overwrite',
                'verbose_name_plural': 'Discord Permission Overwrites',
            },
        ),
        migrations.AlterField(
            model_name='discordchannel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='discord_bot_manager.ChannelTag'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='locked_overwrites',
            field=models.ManyToManyField(to='discord_bot_manager.DiscordOverwrite'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='unlocked_overwrites',
            field=models.ManyToManyField(related_name='unlocked_channel_overwrites', to='discord_bot_manager.DiscordOverwrite'),
        ),
    ]
