# Generated by Django 3.2.5 on 2021-08-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot_manager', '0010_auto_20210831_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordoverwrite',
            name='allow',
            field=models.PositiveBigIntegerField(verbose_name='Allowed Overwrites'),
        ),
        migrations.AlterField(
            model_name='discordoverwrite',
            name='deny',
            field=models.PositiveBigIntegerField(verbose_name='Denied Overwrites'),
        ),
    ]
