# Generated by Django 4.0.4 on 2022-07-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot_manager', '0012_auto_20210831_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='type',
            field=models.IntegerField(choices=[(0, 'GUILD_TEXT'), (1, 'DM'), (2, 'GUILD_VOICE'), (3, 'GROUP_DM'), (4, 'GUILD_CATEGORY'), (5, 'GUILD_NEWS'), (6, 'GUILD_STORE'), (10, 'GUILD_NEWS_THREAD'), (11, 'GUILD_PUBLIC_THREAD'), (12, 'GUILD_PRIVATE_THREAD'), (13, 'GUILD_STAGE_VOICE')], verbose_name='Channel Type'),
        ),
    ]
