# Generated by Django 3.2.3 on 2021-05-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('discriminator', models.IntegerField(blank=True)),
                ('access_token', models.CharField(max_length=40)),
                ('expiry', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
