# Generated by Django 3.2.3 on 2021-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='access_token',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='expiry',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
