# Generated by Django 3.2.5 on 2021-07-08 23:39

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20210530_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Discord ID'),
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=authentication.models.random_token, max_length=64)),
                ('expiry', models.DateTimeField(default=authentication.models.days5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
