# Generated by Django 3.2.5 on 2021-07-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210708_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='delete_immediately',
            field=models.BooleanField(default=True),
        ),
    ]
