# Generated by Django 3.2.5 on 2021-08-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_magiclink_delete_immediately'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduser',
            options={'verbose_name': 'Discord User', 'verbose_name_plural': 'Discord Users'},
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
