# Generated by Django 4.0.6 on 2022-07-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210814_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclink',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
        migrations.DeleteModel(
            name='MagicLink',
        ),
    ]
