# Generated by Django 3.2.3 on 2021-06-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='display_name',
        ),
    ]
