# Generated by Django 3.2.3 on 2021-06-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frosh', '0003_alter_team_coin_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='frosh_team', serialize=False, to='auth.group'),
        ),
    ]
