# Generated by Django 3.2.3 on 2021-06-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0004_alter_team_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('change_team_coin', 'Can change the coin amount of a team.')]},
        ),
    ]
