# Generated by Django 3.2.3 on 2021-06-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0005_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('change_team_coin', 'Can change the coin amount of a team.'), ('view_team_coin_standings', 'Can view the coin standings of all teams.')]},
        ),
    ]
