# Generated by Django 3.2.5 on 2021-08-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frosh', '0006_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FroshRole',
            fields=[
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Role Name')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
            ],
        ),
    ]
