# Generated by Django 3.2.5 on 2021-08-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frosh', '0007_froshrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('pronouns', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pronouns')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='display_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Team Name'),
        ),
    ]
