# Generated by Django 3.2.5 on 2021-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0008_auto_20210808_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='froshrole',
            options={'verbose_name': 'Frosh Role', 'verbose_name_plural': 'Frosh Roles'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('change_team_coin', 'Can change the coin amount of a team.'), ('view_team_coin_standings', 'Can view the coin standings of all teams.')], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Details', 'verbose_name_plural': "Users' Details"},
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Hex Color Code'),
        ),
    ]
