# Generated by Django 3.2.5 on 2021-08-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0009_auto_20210808_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Hex Color Code'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Pronouns'),
            preserve_default=False,
        ),
    ]
