# Generated by Django 3.2.5 on 2021-08-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frosh', '0010_auto_20210813_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Program Name')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
