# Generated by Django 3.2.5 on 2021-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0013_alter_userdetails_invite_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBingoCards',
            fields=[
                ('discord_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('bingo_card', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Discord Bingo Card',
                'verbose_name_plural': 'Discord Bingo Cards',
            },
        ),
    ]
