# Generated by Django 3.2.5 on 2021-09-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0014_discordbingocards'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTeam',
            fields=[
                ('role_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Virtual Team',
                'verbose_name_plural': 'Virtual Teams',
            },
        ),
    ]
