# Generated by Django 3.2.5 on 2021-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0015_virtualteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualteam',
            name='num_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
