# Generated by Django 4.0.6 on 2022-07-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frosh', '0016_virtualteam_num_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordBingoCards',
        ),
        migrations.RemoveField(
            model_name='froshrole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='VirtualTeam',
        ),
        migrations.DeleteModel(
            name='FroshRole',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='UniversityProgram',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
