# Generated by Django 3.2.3 on 2021-06-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Hint ID')),
                ('text', models.CharField(blank=True, max_length=2000, verbose_name='Hint Text')),
                ('file', models.FileField(blank=True, upload_to='scav/questions/')),
                ('image', models.ImageField(blank=True, upload_to='scav/questions/')),
                ('weight', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Question ID')),
                ('text', models.CharField(blank=True, max_length=2000, verbose_name='Text')),
                ('file', models.FileField(blank=True, upload_to='scav/questions/')),
                ('image', models.ImageField(blank=True, upload_to='scav/questions/')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('locked_out_until', models.DateTimeField(blank=True, verbose_name='Locked Out Until')),
                ('last_hint_time', models.DateTimeField(blank=True)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scavenger.question')),
                ('last_hint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='scavenger.hint')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(verbose_name='Completed At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scavenger.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scavenger.team')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Order Number')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scavenger.question')),
            ],
        ),
        migrations.AddField(
            model_name='hint',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scavenger.question'),
        ),
    ]
