# Generated by Django 3.2.3 on 2021-06-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0002_auto_20210605_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Hint ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='questionorder',
            name='order_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='questiontime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
