# Generated by Django 3.2.3 on 2021-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0005_auto_20210605_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
