# Generated by Django 3.2.3 on 2021-06-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0006_alter_question_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='group_id',
            new_name='group',
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scavenger_team', to='scavenger.question'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_hint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scavenger.hint'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_hint_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='locked_out_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked Out Until'),
        ),
        migrations.DeleteModel(
            name='QuestionOrder',
        ),
    ]
