# Generated by Django 3.2.3 on 2021-06-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0007_auto_20210618_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
