# Generated by Django 3.2.3 on 2021-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0008_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
