# Generated by Django 3.2.5 on 2021-08-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0010_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
