# Generated by Django 3.2.5 on 2021-08-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0011_remove_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'verbose_name': 'Scavenger Hint', 'verbose_name_plural': 'Scavenger Hints'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Scavenger Question', 'verbose_name_plural': 'Scavenger Questions'},
        ),
        migrations.RemoveField(
            model_name='hint',
            name='image',
        ),
        migrations.AddField(
            model_name='hint',
            name='display_filename',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='hint',
            name='lockout_time',
            field=models.IntegerField(default=900, verbose_name='Lockout Duration in Seconds'),
        ),
    ]
