# Generated by Django 3.2.5 on 2021-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0012_auto_20210813_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('guess', 'Can guess for scav questions')], 'verbose_name': 'Scavenger Question', 'verbose_name_plural': 'Scavenger Questions'},
        ),
    ]
