# Generated by Django 3.2.5 on 2021-08-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0014_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Scavenger Team', 'verbose_name_plural': 'Scavenger Teams'},
        ),
        migrations.AddField(
            model_name='hint',
            name='cooldown_time',
            field=models.IntegerField(default=None, null=True, verbose_name='Hint Cooldown duration in Seconds'),
        ),
        migrations.AddField(
            model_name='question',
            name='cooldown_time',
            field=models.IntegerField(default=0, verbose_name='Hint Cooldown duration in Seconds'),
        ),
        migrations.AddField(
            model_name='team',
            name='hint_cooldown_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hint Cooldown Until'),
        ),
    ]
