# Generated by Django 3.2.5 on 2021-08-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0015_auto_20210814_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished Scavenger'),
        ),
    ]
