# Generated by Django 3.2.5 on 2021-08-15 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0017_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scavenger_team', to='scavenger.question'),
        ),
    ]
