# Generated by Django 4.0.6 on 2022-07-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0019_remove_questiontime_team_delete_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiontime',
            name='question',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionTime',
        ),
    ]
